language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-7
install:
  - sudo apt-get install doxygen
  - sudo apt-get install graphviz
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .
  - cmake --build .
after_success:
  - doxygen Doxyfile
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -T print_ip-$TRAVIS_BUILD_NUMBER-Linux.deb -uk-streltsov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-streltsov/otus-cpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: html
    verbose: true
    on:
      branch: master